apiVersion: v1
kind: Pod
metadata:
  name: fullapp-pod
spec:
  containers:
    - name: fullapp-container
      image: busybox
      command:
        ["/bin/sh", "-c", "echo APP_ENV=$APP_ENV && echo APP_PORT=$APP_PORT && echo APP_COLOR=$APP_COLOR && echo MAX_CONNECTIONS=$MAX_CONNECTIONS && echo DB_USER=$DB_USER && echo DB_NAME=$DB_NAME && sleep 3600"]
      envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: db-secret
